{
  "hash": "5fd6245b2fe6ef11eb2b31b463eb402d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: UK Excess Deaths by Age Group and Sex\nauthor: Francis J. DiTraglia\ndate: '2020-05-13'\ncategories:\n- applied\ntags:\n- covid\n---\n\n<!--One of the most striking facts about covid has been its disproportionate impact on men and older people.--> \nIn an earlier post I looked at regional differences in the effects of Covid-19 by calculating excess deaths in each week of 2020 relative to an average of the preceding five years. There the idea was to get a sense for the number of deaths that were likely caused by Covid-19 regardless of whether they were officially registered as such, e.g. deaths that occurred outside of hospitals. Thanks to my RA Dan Mead, here's the same analysis carried out by age group and sex rather than region:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Total Weekly Deaths in England & Wales by Sex and Age Group.](index_files/figure-html/plot-1.png){width=672}\n:::\n:::\n\n\nThe red curve is an equally-weighted average of reported weekly deaths for the past five years up to and including 2019, while the blue curve depicts weekly deaths in 2020. All calculations are based on data from the [ONS](https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/datasets/weeklyprovisionalfiguresondeathsregisteredinenglandandwales).\nEach point on the red curve is accompanied by error bars indicating plus/minus two standard errors of the  mean. Roughly speaking these bounds are equivalent to the margin of error from a typical opinion poll. (For the precise calculations, see the R code below.) \n\n\n::: {.cell}\n\n:::\n\n\nDeaths below age 1 show no clear pattern in 2020 relative to the average of past years.\nThere's a hint of slightly *lower* deaths among males aged 1-14 since the lockdown began, although the data are quite noisy given the extremely small number of deaths in this age group. \nFor the remaining age groups, we start to see a clear effect around the time of the covid outbreak, approximately weeks 11 through 22 of 2020.\nBecause death rates vary with age and sex in both ordinary years and 2020, the cleanest way to compare across groups is by computing *relative* excess deaths.\nTo do this, we add up the differences between the red curve and the blue curve between weeks 11 and 22 and divide the result by sum of the red curve during the same period of time. \nThe result give us the percentage by which total deaths in a given age/sex group in weeks 11 through 22 of 2020 exceed the \"usual\" number of deaths for this age/sex group during the same weeks based on past data.\n\nIn the 15-44 age group, male deaths during weeks 11 through 22 of 2020 were 6.4% higher than usual. In contrast, female deaths were 9.7% higher than usual. Deaths in this age group, however, are relatively rare. Accordingly, the blue curves lie comfortably within the error bars for all but a small number of weeks. For the remaining age groups, the picture becomes much starker and the relative excess deaths much larger:\n\n| Age Group     | Men         | Women |\n| ------------- |------------ | ------|\n| 45-64         | +42.2% | +32.4% |\n| 65-74         | +42.9% | +31.6% |\n| 75-84         | +58.2% | +45.5% |\n| Over 85       | +65.3% | +48.5% |\n\nIn each age group, relative excess deaths are substantially higher for men than women. \nFor example, male deaths in the 45-64 age group were 42.2% higher than usual in weeks 11 through 22 of 2020 compared to 32.4% higher for women. Although relative excess deaths increase markedly with age for both sexes, even the rates in the 45-64 group are alarming, particularly for men.\n\nYou can replicate the plot from above by running this R code: \n\n::: {.cell}\n\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}