---
title: Chris Sims - RIP
author: Francis J. DiTraglia
date: '2026-03-15'
categories:
- meta
tags: []
---

I was saddened to hear of Chris Sims's passing yesterday. Although I'm not a macroeconometrician, his work has strongly influenced the way I think about econometrics. I covered his famous [helicopter tour](/post/sims-and-uhlig-1991-replication/) paper on this blog a while back. Some of my other favorites are unpublished notes or slides from his [website](https://www.princeton.edu/~sims), many of them with a philosophical bent. [Thinking about instrumental variables](http://sims.princeton.edu/yftp/IV/IV.pdf) is a paper I read in grad school that really clarified why things can go so badly wrong in IV estimation. I read [Understanding Non-Bayesians](http://sims.princeton.edu/yftp/UndrstndgNnBsns/GewekeBookChpter.pdf) for the first time a couple of years ago and wished I had read it sooner. It articulates a view of Bayesian econometrics that I find particularly compelling. [Robins-Wasserman, Round N](http://sims.princeton.edu/yftp/WassermanExmpl/WassermanR4a.pdf) and [Sharp Econometrics](http://sims.princeton.edu/yftp/SharpEmet/SharpEmet.pdf) have also shaped the approach I'm taking in some [recent work with Laura Liu](https://laurayuliu.com/research/BDML_DL/BDML.pdf).

I didn't know Chris well, but I met him a couple of times early in my career. One of those meetings is particularly memorable. I was invited to give a seminar at Princeton on relatively short notice and was feeling apprehensive. The material that I had ready to present was preliminary and a little unusual: it included elements of my paper on [disciplining beliefs](http://ditraglia.com/pdf/DiTraglia-Garcia-Jimeno-2019.pdf) as well as some more traditional results that eventually made their way into [this paper](http://ditraglia.com/pdf/binary-regressor-final.pdf). 

When I saw that my first meeting of the day was with a Nobel laureate whom I'd never met before, I was even more nervous! But Chris was great; within a couple of minutes I felt completely comfortable talking with him and was genuinely surprised to see how interested he was in hearing my views on econometrics. I don't mean to say that my views were particularly insightful or interesting. I think Chris just genuinely enjoyed engaging with people about econometrics and puzzling through the issues that he found interesting and important. 

Near the beginning of my seminar, someone in the audience asked me a slightly pointed question---not rude but definitely skeptical of my approach. For whatever reason, I got flustered and flubbed my response. I couldn't seem to articulate my point, and then bungled my response to a follow-up question as well. Just when I started to worry that my seminar was going off the rails, Chris chimed in and clarified the point I had been struggling to articulate. I remember feeling incredibly relieved, like someone had just pressed a reset button for my talk. It was just a small thing, but it meant a lot to me at a time in my career when I was feeling anything but confident about my ideas and my work. 


